apiVersion: storage.cloud.atomix.io/v1beta1
kind: RedisStorageClass
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  proxy:
    image: {{ .Values.proxy.repository}}:{{ .Values.proxy.tag }}
