apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redistorages.storage.cloud.atomix.io
spec:
  group:  storage.cloud.atomix.io
  names:
    kind: RedisStorage
    listKind: RedisStorageList
    plural: redistorages
    singular: redisstorage
  scope: Namespaced
  version: v1beta2
  subresources:
    status: {}