apiVersion: storage.cloud.atomix.io/v1beta2
kind: RedisStorage
metadata:
  name: redis-storage
  labels:
    app: redis-storage
spec:
  proxy:
      image: atomix/redis-storage:latest
      livenessProbe:
        tcpSocket:
          port: 5678
          initialDelaySeconds: 15
          periodSeconds: 20
  backend:
      metadata:
        name: redis-storage
        labels:
          app: redis-storage
      image: redis:latest
      replicas: 1
      livenessProbe:
        tcpSocket:
          port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
      readinessProbe:
        exec:
          command:
            - redis-cli
          initialDelaySeconds: 5
          periodSeconds: 5